developersdo/empleo-dot-net

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Models/Database.cs
Me puse a ver los videos, no es mucho lo que hice.
=> Refactoring en el controllador JobOpportunity

EmpleoDotNet/App_Start/RouteConfig.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/PrettyUrlHelper.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Web.config, EmpleoDotNet/packages.config
- Agregando nueva ruta en RouteConfig.
- Agregando nuevo ejemplo de como llamar dicha ruta en Index.cshtml
- Agregando paquete RouteDebugger para visualizar las rutas creadas
=> Pretty URL

EmpleoDotNet/App_Start/RouteConfig.cs
@amhed  este el pull resquest valido ya que el otro lo puedes borrar, fue que aprendiendo a utilizar el rebase hice una cuenta pruebas y ya tenia mucho problema que nisiquiera me subía cambio mi repo entonce procedí hacer un nuevo flork y subir ese cambio nuevamente.
=> Haciendo cambio en ruta details para mejor visualización

EmpleoDotNet/Content/Site.css, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/Shared/_LastestJobs.cshtml
Ahora si esta correctamente estructurado el pull request.
=> Limpieza de nombre de clases

EmpleoDotNet/Content/PagedList.css, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Models/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet/Models/Dto/PagedResult.cs, EmpleoDotNet/Models/Repositories/IJobOpportunityRepository.cs, EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Web.config, EmpleoDotNet/packages.config
- Se agrego libreria para paginacion [X.PagedList.Mvc] (https://github.com/kpi-ua/X.PagedList)
- Se agrego un metodo en JobOpportunityRepository para realizar las consultas paginadas
- Se modifico el View de JobOpportunities para mostrar un toolbar para la paginacion
UI Changes
=> Paginacion Lista de Trabajos

EmpleoDotNet/App_Start/BundleConfig.cs, EmpleoDotNet/Views/Shared/_Layout.cshtml
- Bug-fixed when deploy to azure related to css main style resolution path
=> Bug fix css resolution when deploy to azure

EmpleoDotNet.sln, EmpleoDotNet/Controllers/CreditsController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/Credits/Index.cshtml
Atendiendo el issue https://github.com/developersdo/empleo-dot-net/issues/106 los perifles se toman de https://api.github.com/repos/developersdo/empleo-dot-net/contributors
=> Added credits page and stuff

.gitignore, EmpleoDotNet/Content/css/theme/style.css, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/Credits/Index.cshtml, EmpleoDotNet/Views/Home/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
Modificadas las vistas para mostrar el Display attribute value del Enum JobCategory
**Home/Index**
**JobOpportunity/Index**
**JobOpportunity/Detail/###**
Se modifico el margin-top del section 'title' porque daba un error al mostrarse en una pantalla mas chicha
Error
Ready
Se agrego un link a la pagina de agradecimientos
- Se agrego un link al url de la empresa en el logo del view JobOpportunity/Detail 
- Se reemplazo la palabra 'Vacante' por 'Empleo'
=> Mostrar el DisplayAttribute del Enum JobCategory and more

EmpleoDotNet/Views/Home/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
Cuando tengamos el logo se pone el og:image con el logo de la plataforma. Por ahora estoy poniendo la imagen de la empresa en los anuncios y sin imágen en las demás pantallas.
=> Added og metatags

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/QueryableExtensions.cs, EmpleoDotNet/Models/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet/Models/Repositories/IJobOpportunityRepository.cs, EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml
- Issue #131 done!
- Posibilidad de buscar empleos con un keyword usando FTS
- Se introdujo metodo extensor para IQueryable que permite buscar con LIKE en todos los campos strings. Se utilizo el codigo de este [link](http://manfred-ramoser.blogspot.com/2009/09/full-text-search-for-entity-framework.html)
- UI Changes
**Lista no filtrada**
**Lista filtrada**
**Lista sin resultados de busqueda**
=> Buscar empleos con un keyword usando FTS

EmpleoDotNet.Tests/App.config, EmpleoDotNet.Tests/EmpleoDotNet.Tests.csproj, EmpleoDotNet.Tests/EntityFrameworkUnitOfWorkTest.cs, EmpleoDotNet.Tests/Properties/AssemblyInfo.cs, EmpleoDotNet.Tests/packages.config, EmpleoDotNet.sln, EmpleoDotNet/Controllers/AccountController.cs, EmpleoDotNet/Controllers/EmpleoDotNetController.cs, EmpleoDotNet/Controllers/HomeController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs
Ahora mismo solo es un proyecto vacio con un test de ñapa para comenzar.
Se estaría utilizando mientras tanto
- NUnit 2.x
- FluentAssertions
- NSubstitute
=> Creación de proyecto para tests

EmpleoDotNet/Views/Shared/_Layout.cshtml
- Cambiada la posicion del icono del Menu
- Done #137
=> Posición del Icono del Menu

EmpleoDotNet/Views/JobOpportunity/Detail.cshtml
Fixed #149. Corrigiendo que el usuario no salga de la aplicación al momento de acceder a un sitio externo.
=> Corrigiendo redireccionamiento hacia aplicaciones externas

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Models/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet/Models/JobCategory.cs, EmpleoDotNet/Models/Repositories/IJobOpportunityRepository.cs, EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml
Issue #84 
- Agregado filtro de Categorías a la lista de JobOpportunities
=> Filtrar lista de trabajo por categorias

EmpleoDotNet/Content/css/theme/style.css, EmpleoDotNet/Models/JobOpportunity.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml
- Issue #157 
- Desplegar cantidad de trabajos disponibles para una busqueda
=> Desplegar cantidad de trabajos disponibles

EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/HtmlHelperExtensions.cs, EmpleoDotNet/Views/Shared/_Layout.cshtml
- Display Assembly Version Number in Footer
=> Display Assembly Version

EmpleoDotNet.Tests/EmpleoDotNet.Tests.csproj, EmpleoDotNet.Tests/Helpers/EnumerableExtensionsTest.cs, EmpleoDotNet/Helpers/EnumHelper.cs, EmpleoDotNet/Helpers/EnumerableExtensions.cs, EmpleoDotNet/Helpers/HtmlHelperExtensions.cs, EmpleoDotNet/Helpers/JobOpportunityDescriptionBuilder.cs, EmpleoDotNet/Helpers/PrettyUrlHelper.cs, EmpleoDotNet/Helpers/QueryableExtensions.cs
- Ejemplos de unit testing
- Cleanup en estilo y espacios en folder /Helpers
=> Unit Testing 101

EmpleoDotNet/Content/findJob.css, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Models/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs, EmpleoDotNet/Services/JobOpportunityService.cs, EmpleoDotNet/Services/LocationService.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/Shared/_FindJobsPartial.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
- Agregada nueva forma de búsqueda de trabajos
- Se puede buscar directamente por keywords específicos
- Se puede buscar por **Categorías**
- Refactorizado el JobOpporitunityController
- Se agregaron clases para remover los repositorios
=> Buscar Vacantes

EmpleoDotNet/Views/JobOpportunity/Detail.cshtml
- #176 
- Lógica agregada para solo presentar el div con la información de los demás ofertas de una empresa si no posee otras ofertas
**Con mas ofertas de trabajo**
**Sin ofertas**
=> Mas empleos de esta compañia 

EmpleoDotNet.Data/EmpleadoContext.cs, EmpleoDotNet.Repository/BaseRepository.cs, EmpleoDotNet.Repository/Contracts/IBaseRepository.cs, EmpleoDotNet.Repository/Contracts/IJobOpportunityRepository.cs, EmpleoDotNet.Repository/Contracts/ILocationRepository.cs, EmpleoDotNet.Repository/Contracts/ITagRepository.cs, EmpleoDotNet.Repository/EmpleoDotNet.Repository.csproj, EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet.Repository/LocationRepository.cs, EmpleoDotNet.Repository/TagRepository.cs, EmpleoDotNet/App_Start/BundleConfig.cs, EmpleoDotNet/App_Start/EmpleadoModule.cs, EmpleoDotNet/App_Start/FilterConfig.cs, EmpleoDotNet/App_Start/NinjectWebCommon.cs, EmpleoDotNet/App_Start/RouteConfig.cs, EmpleoDotNet/Controllers/EmpleoDotNetController.cs, EmpleoDotNet/Controllers/HomeController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Services/IJobOpportunityService.cs, EmpleoDotNet/Services/ILocationService.cs, EmpleoDotNet/Services/JobOpportunityService.cs, EmpleoDotNet/Services/LocationService.cs, EmpleoDotNet/Startup.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/ViewModel/NewJobOpportunityViewModel.cs, EmpleoDotNet/packages.config
#196
Recomendable ver cada commit por separado: en el primero pongo las clases de repo/servicio/controller DI friendly, y en el segundo uso un IoC container real.
=> Implementando Inversion of Control (IoC) 

EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/DateTimeExtensions.cs, EmpleoDotNet/Views/Home/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/Index.cshtml
=> Agregado formato más legible para las fechas en los empleos.

EmpleoDotNet/Content/Site.css, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
=> Espacio de mas entre el error alert y el content Issue #214

EmpleoDotNet/Content/Site.css, EmpleoDotNet/Helpers/HtmlHelperExtensions.cs, EmpleoDotNet/Views/Home/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
Agregada lógica para utilizar las iniciales del nombre de la comprañia si esta no posee un logo
=> Modificada Home-Index y JobOportunity-Index V1 ISSUE #200

EmpleoDotNet.AppServices/EmpleoDotNet.AppServices.csproj, EmpleoDotNet.AppServices/IJobOpportunityService.cs, EmpleoDotNet.AppServices/ILocationService.cs, EmpleoDotNet.AppServices/JobOpportunityService.cs, EmpleoDotNet.AppServices/LocationService.cs, EmpleoDotNet.AppServices/Properties/AssemblyInfo.cs, EmpleoDotNet.AppServices/ViewModel/RelatedJobDto.cs, EmpleoDotNet.AppServices/packages.config, EmpleoDotNet.Data/EmpleadoContext.cs, EmpleoDotNet.Repository/Contracts/IJobOpportunityRepository.cs, EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet.sln, EmpleoDotNet/App_Start/EmpleadoModule.cs, EmpleoDotNet/Controllers/HomeController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Web.config
What changed:
- Moved services folder to EmpleoDotNet.AppServices.
- Changed search criteria for related jobs.
=> Moved services folder to a new project.

EmpleoDotNet/Properties/AssemblyInfo.cs
- Restored assembly version 1.0.0.0
=> Assembly version

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Web.config, EmpleoDotNet/packages.config
=> Requerir captcha nueva publicación Issue #172

EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/Shared/_FindJobsPartial.cshtml
- Added REMOTO? parameter in FindJobsPartial View
- Added Logic to handle search
- Removed unused code
- Removed Paginador in search result
**UI Changes**
=> Find Remote Jobs

EmpleoDotNet/Views/Shared/_FindJobsPartial.cshtml
- Resolve #253 
- Before: 
- After:
=> Fixed html structure and removed duplicate input

EmpleoDotNet/App_Readme/Elmah.txt, EmpleoDotNet/App_Start/FilterConfig.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/Shared/_JobListPartial.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml, EmpleoDotNet/Web.config, EmpleoDotNet/packages.config
=> Added ELMAH 

EmpleoDotNet.AppServices/IJobOpportunityService.cs, EmpleoDotNet.AppServices/JobOpportunityService.cs, EmpleoDotNet.Core/Dto/JobCategoryCountDto.cs, EmpleoDotNet.Core/EmpleoDotNet.Core.csproj, EmpleoDotNet.Repository/Contracts/IJobOpportunityRepository.cs, EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet/Controllers/HomeController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/Shared/_FindJobsPartial.cshtml
- Added Job Count by Category in Search parameters
**UI Changes**
=> Display Job Count by Category in Search

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/Alerts/Alert.cs, EmpleoDotNet/Helpers/Alerts/AlertDecoratorResult.cs, EmpleoDotNet/Helpers/Alerts/AlertExtensions.cs, EmpleoDotNet/Helpers/BoolExtensions.cs, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Views/JobOpportunity/_JoelTestResults.cshtml, EmpleoDotNet/Views/Shared/_Alerts.cshtml, EmpleoDotNet/Views/Shared/_Layout.cshtml
Lo primero es que el display del joel test ahora se lee mejor en mi opinión
**Antes**
**Después**
Lo otro es que las alertas no usan el viewbag, se pueden agregar varias alertas y se agregan a través de una extensión del ActionResult.
=> Haciendo refactorings de cosas visuales

EmpleoDotNet.Repository/JobOpportunityRepository.cs
- Fix search query related to PR #265
=> Hotfix search query

EmpleoDotNet/App_Start/RouteConfig.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs
- Added new route configuration for the JobOpportunity controller
- Made all routes lower case
- #263
=> Friendly Urls for jobs

EmpleoDotNet.Core/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet.Repository/Dto/NearbyJobOpportunityLocation.cs, EmpleoDotNet.Repository/EmpleoDotNet.Repository.csproj, EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/ViewModel/JobOpportunitySearchViewModel.cs, EmpleoDotNet/Views/Home/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/Index.cshtml, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Views/Shared/_FindJobsPartial.cshtml, EmpleoDotNet/Views/Shared/_JobListPartial.cshtml
- Refactor the common logic to search jobs
- Added logic to search nearby locations
- Disabled auto-complete of location related to issue #271
- Added validation for location when search jobs and new job
=> Fix Geolocation Search

EmpleoDotNet/App_Start/FilterConfig.cs, EmpleoDotNet/Controllers/UnderMaintenanceController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/UnderMaintenanceFilterAttribute.cs, EmpleoDotNet/Views/Shared/_Layout.cshtml, EmpleoDotNet/Views/UnderMaintenance/Index.cshtml, EmpleoDotNet/Web.config
- Added Global Action Filter to detect and handle every request
- Added view under maintenance
- Addressed Issue #258 
- Added Feature Flag to web.config
=> Added Under Maintenance Feature

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml
- Fixed Unformatted text on Detail view
- Bugfix null id when navigate to Detail view
- Addressed issues #259 #250  
**Before**
**After**
=> Fix unformatted text

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Properties/AssemblyInfo.cs, EmpleoDotNet/Views/JobOpportunity/Index.cshtml
Hotfix unmapped pagination parameters
=> Hotfix paginatin

EmpleoDotNet.Tests/EmpleoDotNet.Tests.csproj, EmpleoDotNet.Tests/Web/Controllers/CreditsControllerTest.cs, EmpleoDotNet.Tests/Web/Controllers/ErrorControllerTest.cs, EmpleoDotNet.Tests/Web/Controllers/HomeControllerTest.cs, EmpleoDotNet.Tests/Web/Controllers/JobOpportunityControllerTest.cs, EmpleoDotNet.Tests/Web/Controllers/UnderMaintenanceControllerTest.cs, EmpleoDotNet.Tests/packages.config, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/CookieHelper.cs, EmpleoDotNet/Services/Social/Twitter/ITwitterService.cs, EmpleoDotNet/Web.config, EmpleoDotNet/packages.config
- HomeControllerTest
- CreditControllerTest
- ErrorControllerTest
- UnderMaintenanceControllerTest
- Skeleton for JobOpportunityControllerTest
- Updated a few unit testing nuget packages
- Added a few extra nuget packages to the test assembly to erase compiler warnings
=> Added Controller Tests

README.md
Added a link to the wiki, so the reference is kept even in local repos; rephrased some sentences to improve reading flow; a link to developers do and c# do should be added.
=> Refreshed the readme to avoid staleness

EmpleoDotNet.Core/Domain/JobCategory.cs
-it's added a new job category "Desarrollo de Videojuegos" as requested in  #306.
=> Added new Job Category, Desarrollo de videojuegos.

EmpleoDotNet/Content/JobOpportunity/Detail.css, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/JobOpportunity/HtmlPage1.html
Este pull request es para solucionar el problema del issue #283.
> Foto original: http://images.artelista.com/artelista/obras/big/7/6/1/3782168383467791.jpg
=> Se cambio el height del logo de compañia

Mobile/Android/Android.csproj, Mobile/Android/JobDetail/JobDetailActivity.cs, Mobile/Android/LandingPage/LandingPageActivity.cs, Mobile/Android/MainPage/MainPageActivity.cs, Mobile/Android/Resources/layout/JobDetailActivityLayout.axml, Mobile/Android/Resources/values/attr.xml
This pull request is related to #325 issue
- Implemented the layout for job detail screen and it looks like this
=> Implement the layout for job detail

Mobile/Android/Android.csproj, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/MainPage/FavoritesFragment.cs, Mobile/Android/MainPage/FavoritesViewModel.cs
This issue is related to #356 
- The favorite feature from MainPage that list the user favorite jobs
=> Implement favorite feature

Mobile/Android/Android.csproj, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/Framework/ViewModelBase.cs, Mobile/Android/MainPage/Converters.cs, Mobile/Android/MainPage/JobsFragment.cs, Mobile/Android/MainPage/JobsFragmentViewModel.cs, Mobile/Android/MainPage/MainPageFragment.cs, Mobile/Android/MainPage/MainPageFragmentViewModel.cs, Mobile/Android/MainPage/NotifyUserChangedQuery.cs, Mobile/Android/MainPage/NotifyUserClearedText.cs, Mobile/Android/MainPage/ViewStateToBool.cs, Mobile/Android/Resources/layout/JobsFragmentLayout.axml, Mobile/Android/Resources/values/Strings.xml, Mobile/Android/Services/IJobRepository.cs, Mobile/Core/Bind.cs, Mobile/Core/Core.csproj, Mobile/Core/IValueConverter.cs
- Implemented:
1. **Empy state** When you type text into the search bar
2. **Loading state** When the query was not found into the servers
=> Create state for job feature

EmpleoDotNet/EmpleoDotNet.csproj
CI was borken because of this ):
=> Removed reference to missing file

EmpleoDotNet/Web.config
=> Fix connection string.

Mobile/Android/Android.csproj, Mobile/Android/Empleado.cs, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/Resources/layout/LandingPageFragmentLayout.xml, Mobile/Android/Resources/layout/LandingPageLayout.axml, Mobile/Android/Services/AppInfoService.cs, Mobile/Android/Services/XMLStorage.cs, Mobile/Android/SplashScreen/SplashActivity.cs, Mobile/Android/SplashScreen/SplashViewModel.cs, Mobile/Core/Core.csproj, Mobile/Core/IAppInfoService.cs, Mobile/Core/IXMLStorage.cs
If it is the first time you enter the app, the app will show you the **Landing Page**
If you have opened the app before then the app will show you the **Main Screen**
1. **IXMLStorage**
A lightweight persistent storage alternative to **Akavache** that save content into a **XML** file.
2. **IAppInfoService**
Abstract basic information to the **Manifest** like **VersionCode** and **VersionName**
=> Show the landing page if its the first time the user enters the app

Mobile/Android/Properties/AndroidManifest.xml
This will allow the project to run on Android devices running version 4.1 or newer.
Fixes #401
=> Add support for Android Jelly Bean (4.1)

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Scripts/JobOpportunity/Wizard.js, EmpleoDotNet/Views/JobOpportunity/Wizard.cshtml
Error summary on wizard screen (#329)
When you click on an error message, the field with the validation error get focused so you don't have to go to the page manually.
=> Error summary on wizard screen.

CONTRIBUTING.md, README.md
#350 
- Added contributing file.
- Moved contributing guidelines from readme.md to contributing.md.
=> Contributing guidelines.

EmpleoDotNet/Content/JobOpportunity/Wizard.css, EmpleoDotNet/Views/JobOpportunity/Wizard.cshtml
Wizard steps are responsive now. Related issue #386 
Screenshots:
=> Making wizard steps responsive.

Mobile/Android/About/AboutActivity.cs, Mobile/Android/About/AboutViewModel.cs, Mobile/Android/About/ContributorAddedEventHandler.cs, Mobile/Android/Android.csproj, Mobile/Android/Empleado.cs, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/MainPage/MainPageActivity.cs, Mobile/Android/MainPage/MainPageActivityViewModel.cs, Mobile/Android/MainPage/MainPageFragmentViewModel.cs, Mobile/Android/MainPage/OptionMenu.cs, Mobile/Android/MainPage/ShowAs.cs, Mobile/Android/Resources/layout/AboutLayout.axml, Mobile/Android/Resources/layout/ContributorItem.axml, Mobile/Android/Resources/menu/MainPageActivityMenu.xml, Mobile/Android/Resources/values/Strings.xml, Mobile/Core/Core.csproj, Mobile/Core/Github/GithubUser.cs, Mobile/Core/Github/IGithubContributorService.cs, Mobile/Core/Github/OctocatContributorService.cs, Mobile/Core/packages.config, Mobile/Mobile.userprefs
1. About page which include
- List of contributors
- Brief project description
This pull request also include a new service
- **IGithubContributorService** which return a list of contributors from a project based on their merged PR
=> Implement about page into the android project

Mobile/Android/Android.csproj, Mobile/Android/Properties/AndroidManifest.xml, Mobile/Android/Resources/layout/JobDetailActivityLayout.axml
Incremented version to upload APK to [HockeyApp](https://rink.hockeyapp.net/apps/67554952ba5d4cc1ac4aca170f3f8e72/app_versions/2)
=> Get app ready for HockeyApp

Mobile/APIs/FakeJobsApiService.cs, Mobile/Android/Android.csproj, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/MainPage/JobDetailFragment.cs, Mobile/Android/MainPage/JobDetailFragmentViewModel.cs, Mobile/Android/MainPage/JobsFragmentViewModel.cs, Mobile/Android/Resources/layout/JobDetailActivityLayout.axml, Mobile/Android/Services/EmailService.cs, Mobile/Api.Contract/JobDetailResponse.cs, Mobile/Core/Core.csproj, Mobile/Core/Services/IEmailService.cs
Fixes #406
Bind the views of the JobDetailFragment to the Properties of its ViewModel.
Add IEmailService and its implementation on Android. This opens the chooser and lets the user send an email from their preferred email client.
=> Bind the JobDetail Fragment

Mobile/Android/Android.csproj, Mobile/Android/Empleado.cs, Mobile/Android/EmpleadoApp.cs, Mobile/Android/packages.config
- Integrated [Xamarin Insight](https://developer.xamarin.com/guides/insights/platform-features/catching-exceptions/) into the Android project to report crashes.
=> Integrate Xamarin Insight into the Android project

Mobile/Android/Android.csproj, Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs, Mobile/Android/MainPage/MainPageFragment.cs, Mobile/Android/Resources/layout/MainPageFragmentLayout.axml, Mobile/Android/Services/KeyboardService.cs, Mobile/Core/Core.csproj, Mobile/Core/IKeyboardService.cs
- Removed the focus when the MainPage is shown up so the keyboard does not hide the screen
=> Hide keyboard on MainPage when the app start

EmpleoDotNet.Tests/Web/Controllers/JobOpportunityControllerTest.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/UrlHelperExtensions.cs
Add validation to image URL, according to #405
=> Add company initials when image is unavailable

EmpleoDotNet.Tests/Services/Twitter/TwitterServiceTests.cs, EmpleoDotNet.Tests/Web/Controllers/JobOpportunityControllerTest.cs, EmpleoDotNet/Controllers/AccountController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Helpers/UrlHelperExtensions.cs, EmpleoDotNet/Services/Social/Twitter/ITwitterService.cs, EmpleoDotNet/Services/Social/Twitter/TwitterService.cs, README.md
Update Url format for tweet according to #336
=> Update URL format for Tweet 

EmpleoDotNet.Tests/Services/Twitter/TwitterServiceTests.cs, EmpleoDotNet/Services/Social/Twitter/TwitterService.cs
Adds a hashtag (#weworkremotely) to the tweet sent when someone adds a
position which is remote.
Solves #380
=> Adds #weworkremotely to tweets of remote jobs.

EmpleoDotNet/Views/JobOpportunity/Index.cshtml
Adds Keyword, JobCategory and IsRemote to the PagedListPager parameter.
Fixes Pagination for Searches with keywords, Categories and IsRemote
filters.
Resolves #395
=> Add missing Properties to PagedListPager parameters

EmpleoDotNet/Content/css/theme/style.css
This address issue #447 
Before
updated
=> Corrected Edit button UI Error

EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/Views/Shared/_JobListPartial.cshtml
=> Fix edit button been active for anonymous user.

Mobile/Android/MainPage/MainPageActivityViewModel.cs, Mobile/Android/MainPage/MainPageFragment.cs, Mobile/Android/MainPage/PagerAdapter.cs
- Remove favorites tab
- Remove contributors tab
=> Remove non-mvp functionality from the project

Mobile/Android/Assets/MobileConfig.json, Mobile/Android/Properties/AndroidManifest.xml
- Added key to Manifest for Google Places API
- Added key to Assets/MobileConfig.json for Tamarin Insight
=> Integrate missing API keys into the project

Mobile/Android/MainPage/MainPageFragment.cs, Mobile/Android/Resources/layout/MainPageFragmentLayout.axml
Removed the ability to filter the location by places since it is not a **non-mvp-feature**
=> Remove filter location screen from the MainPage

EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/JobOpportunity/New.cshtml, EmpleoDotNet/Views/JobOpportunity/Wizard.cshtml
According to #475, show company email regardless of "how to apply" content.
=> show company email on job opportunity

EmpleoDotNet/Content/css/theme/style.css, EmpleoDotNet/Views/Shared/_Layout.cshtml
The footer now is positioned at the bottom, regardless of the content:
- Issue: #442 
- Live: [CodePen](http://codepen.io/Elienet/pen/MyzgJQ)
=> Add Sticky Footer

EmpleoDotNet/Scripts/app.js
Added javascript method to only submit parameters if they contain value (when the form's method is get)
This pull request address issue #446 
Before
After
=> Friendly search URL

EmpleoDotNet/Controllers/AccountController.cs, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj
According to Issue #457, this should avoid that to happen.
Sorry I also changed AccountCountroller.cs but I couldn't let "this" to be there. 😜
=> Adding a new job Opportunity set  views to "1"

Mobile/APIs/APIs.csproj, Mobile/APIs/packages.config, Mobile/Android/Android.csproj, Mobile/Android/packages.config, Mobile/Api.Contract/Api.Contract.csproj, Mobile/Api.Contract/IJobsApiService.cs, Mobile/Api.Contract/packages.config
- Removed Refit reference from each project
=> Remove Refit reference from each project

EmpleoDotNet.AppServices/IJobOpportunityService.cs, EmpleoDotNet.AppServices/JobOpportunityService.cs, EmpleoDotNet/Content/Site.css, EmpleoDotNet/Content/css/theme/style.css, EmpleoDotNet/Controllers/JobOpportunityController.cs, EmpleoDotNet/EmpleoDotNet.csproj, EmpleoDotNet/Scripts/app.js, EmpleoDotNet/Views/JobOpportunity/Detail.cshtml, EmpleoDotNet/Views/Shared/_ConfirmDeleteModal.cshtml, EmpleoDotNet/Views/Shared/_JobListPartial.cshtml
According to #435.
* En el listado de mis posiciones debo ver un botón de eliminar
* En el detalle de mi posición debo ver un botón de eliminar
* Antes de eliminar una posición debe pedirme confirmación
* Al eliminar una posición debe mostrarme un mensaje de que la posición fue exitosamente eliminada
* Jobs list
* Job Detail
* Delete Confirm
=> User can delete created job opportunity

EmpleoDotNet/Helpers/HtmlHelperExtensions.cs
According to #487 and I also  ignored numbers
=> Add initials only if is a valid value

EmpleoDotNet.Core/Domain/JobCategory.cs, EmpleoDotNet.Core/Dto/JobOpportunityPagingParameter.cs, EmpleoDotNet.Repository/JobOpportunityRepository.cs, EmpleoDotNet.Tests/Web/Controllers/JobOpportunityControllerTest.cs, EmpleoDotNet/Views/JobOpportunity/New.cshtml
According #272 
* Remove categories invalid and todas
* Remove white space on dropdown list for job category and job type
SQL Query for Data Quality 
```sql
update JobOpportunities
set Category = 8 
where Category = -1 or category = -2
```
=> Remove invalid and "todas" from job category

EmpleoDotNet/Scripts/app.js
=> Fix search not working on CI
