developersdo/empleo-dot-net

EmpleoDotNet/Migrations/Configuration.cs

Fixing seed method by saving the locations to the db before using them in the job opportunities.
The code was using temporary Ids for the locations, and this caused errors when running the seed method, the solution was to force Entity framework to save the locations before using them, and that made them have the correct Ids.

Fixing seed method 

---

EmpleoDotNet/Models/Repositories/BaseRepository.cs
EmpleoDotNet/Models/Repositories/JobOpportunityRepository.cs
EmpleoDotNet/Models/Repositories/LocationRepository.cs
EmpleoDotNet/Models/Repositories/TagRepository.cs
EmpleoDotNet/Web.config

The Base repository had the correct implementation to save the entities, because it sets up it's dbSet in the default constructor, the problem was that the derivated repositories didn't call that constructor nor set up the dbSet, so the repository didn't have the ability to save new entities.
I just added the dbSet setup to one of the baseRepository constructors, and call it from each of the derivated repositories.

Fixing Add issue with the repositories

---

EmpleoDotNet/Controllers/AccountController.cs
EmpleoDotNet/Controllers/CreditsController.cs
EmpleoDotNet/EmpleoDotNet.csproj
EmpleoDotNet/Models/EntityFrameworkUnitOfWork.cs
EmpleoDotNet/Models/Repositories/BaseRepository.cs
EmpleoDotNet/Models/Repositories/ILocationRepository.cs
EmpleoDotNet/Models/Repositories/ITagRepository.cs
EmpleoDotNet/Models/Repositories/TagRepository.cs
EmpleoDotNet/Models/TableConfigurations/BaseTableConfiguration.cs
EmpleoDotNet/Models/TableConfigurations/JobOpportunityTableConfiguration.cs
EmpleoDotNet/Models/Tag.cs
EmpleoDotNet/Views/Home/Index.cshtml
EmpleoDotNet/Views/Shared/_LastestJobs.cshtml
EmpleoDotNet/Web.config
EmpleoDotNet/packages.config

Para el código en C# no hubo que hacer nada. Simplemente cambié algunas cosas a C# 6 y compiló solo en VS 2015.
Para usarlo en Razor files hubo que descargar este nuget package: http://stackoverflow.com/a/30832849/2563028
Eso será un polyfill temporal hasta que migremos a ASP.NET 5 con MVC 6.
Aproveché e hice un poco de cleanup.

Habilitar C# 6 en EmpleoDotNet

---

EmpleoDotNet/Content/css/theme/style.css
EmpleoDotNet/Controllers/JobOpportunityController.cs
EmpleoDotNet/Views/JobOpportunity/Detail.cshtml
EmpleoDotNet/Views/JobOpportunity/New.cshtml
EmpleoDotNet/Web.config

- Fixed #142 Icono mal posicionado en la vista movil
**Relacionado al issue #124, claro, no el release final**
- Poder dar estilo a la descripcion del mensaje
- Removida dependencia del helper JobOpportunityDescriptionBuilder
- Agregado atributo ValidateInput(false) en metodo del New del JobOpportunityController
**Input**
**Detail**

 Fixed Icono mal posicionado y Dar estilo al texto de la descripción del puesto

---

EmpleoDotNet/Scripts/app.js

Como anteriormente se tenia una un banner de portada en el home page había un validación para cambiarle el color a los íconos del menú siempre y cuando no se estuviese en el home, pero como ya se quitó dicho banner esta validación ya no es necesaria.
#201

Quita la validación del cambio de color de los íconos del menú

---

EmpleoDotNet/Scripts/app.js
EmpleoDotNet/Scripts/theme/settings.js

Se removio el codigo para que a pesar de que se haga scroll en la pagina siempre se muestre el header (no se vuelva transparente) segun el issue #203
Antes
Ahora

Header siempre visible

---

EmpleoDotNet/Views/Credits/Index.cshtml

El pronombre **_tú_** lleva acento, en una oración no lo tenía.
La forma correcta de escribir el verbo haber en modo imperativo es **HAZ**. Actualmente dice _has un pull request_ . **_Has_** corresponde a la segunda persona singular del modo indicativo , tiempo presente del verbo haber, ejemplo : "Tú has cambiado mucho"

Arreglando falta ortográfica verbo haber modo imperativo y pronombre tú

---

EmpleoDotNet/Views/JobOpportunity/New.cshtml

The link was located in http://localhost:18661/JobOpportunity/New and contained and unnecessary space causing a 404 error page to appear.

Fixed broken link pointing to the new job opportunity wizard.

---

EmpleoDotNet/Content/JobOpportunity/Wizard.css
EmpleoDotNet/Controllers/JobOpportunityController.cs
EmpleoDotNet/Scripts/JobOpportunity/Wizard.js
EmpleoDotNet/Views/JobOpportunity/Wizard.cshtml

- Removed dots at the bottom of the wizard
- Added visual aid to show user the current step and the remaining ones (view screen shot)
- Corrected bug that allowed user to change pages without validating the current one.
- Added google's recaptcha to view
**What I need help with**
- Form is sumitted even if captcha is not valid
- New round step buttons not aligning properly on mobile.
**Related issues**
- #228 Navegación proceso guíado de creación de posiciones
- #247

Corrected problems with new job wizard.

---

EmpleoDotNet/Web.config

Para evitar problemas de este tipo: 
No tengo nada instalado para probar este cambio, ¿alguien puede probar este cambio y confirmar que funciona?

Establecer codificación global como UTF-8

---

EmpleoDotNet.Tests/EmpleoDotNet.Tests.csproj
EmpleoDotNet.Tests/Web/Controllers/JobOpportunityControllerTest.cs
EmpleoDotNet.Tests/packages.config
EmpleoDotNet/Controllers/JobOpportunityController.cs
EmpleoDotNet/Helpers/Alerts/AlertExtensions.cs
EmpleoDotNet/Services/Social/Twitter/TwitterService.cs
EmpleoDotNet/ViewModel/NewJobOpportunityViewModel.cs

Hice los tests para un action "peñoncito" de probar. Quiero ver si con eso y con el test que hice para el cookie helper la gente se anima a escribir unit tests para los actions importantes que quedan en el JobOpportunityController: Detail y Wizard.
También aproveché para hacer el task en #288 e hice algo de cleanup: en el método ToEntity del viewmodel, el `if` que había era innecesario porque la aplicación nunca llegaba a ese punto. El ModelState estaba malo ya cuando el LocationName o el LocationPlaceId estaban nulos o vacíos.

Added JobOpportunityController tests for the "New" actions

---

EmpleoDotNet.Tests/EmpleoDotNet.Tests.csproj
EmpleoDotNet.Tests/Web/Helpers/CookieHelperTest.cs
EmpleoDotNet.Tests/Web/Helpers/TrimModelBinderTest.cs
EmpleoDotNet/Code/EmpleoDotNetHttpContext.cs
EmpleoDotNet/Code/TrimModelBinder.cs
EmpleoDotNet/EmpleoDotNet.csproj
EmpleoDotNet/Global.asax.cs
EmpleoDotNet/Helpers/CookieHelper.cs

#299
En buena medida lo hice gracias a este post de stackoverflow: http://stackoverflow.com/a/1734025/2563028
sin embargo cuando escribí el test para verificar el trimming en el caso donde el parámetro que se pasa al action es un string simple, me estaba fallando, así que le hice override a BindModel también para poder hacer trim ahí.
Otra cosa que hice fue que cambié el nombre del namespace Core en el proyecto web EmpleoDotNet a EmpleoDotNet.Code para que no se confundiera con el proyecto EmpleoDotNet.Core

Created Trim Model Binder

---

Mobile/Android/Resources/values/themes.xml

- Now the mobile app theme is matching the web version theme.

Match the web theme version on mobile

---

Mobile/Android/Resources/layout/JobCardLayout.axml
Mobile/Android/Resources/layout/JobsFragmentLayout.axml
Mobile/Android/Resources/layout/MainPageLayout.axml
Mobile/Android/Resources/values/Strings.xml

- Give more padding to cards relativa to each other
- Change the background
- Fixed an issue that caused the right arrow to be wrapped to the right

Improve jobs layout from MainPage

---

Mobile/Android/Android.csproj
Mobile/Android/Empleado.cs
Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs
Mobile/Android/MainPage/MainPageActivity.cs
Mobile/Android/MainPage/MainPageFragment.cs
Mobile/Android/MainPage/MainPageFragmentViewModel.cs
Mobile/Android/Resources/layout/MainPageFragmentLayout.axml
Mobile/Android/Resources/layout/MainPageLayout.axml
Mobile/Android/Resources/layout/SearchActivityLayout.axml
Mobile/Android/Resources/values/Strings.xml
Mobile/Android/Resources/values/themes.xml
Mobile/Android/SearchPage/SearchActivity.cs

This issue is related to #362 
- Now when you click on the right arrow from main page it takes you to the search filter location.
I made the filter location an Activity because the way the SearchView is positioned on the screen make it really difficult to navigate between fragment.

Create transition between mainpage to filter search

---

Mobile/Android/Android.csproj
Mobile/Android/MainPage/FavoritesFragment.cs
Mobile/Android/MainPage/FavoritesViewModel.cs
Mobile/Android/MainPage/JobsFragmentViewModel.cs
Mobile/Android/MainPage/MainPageFragment.cs
Mobile/Android/MainPage/MainPageFragmentViewModel.cs
Mobile/Android/MainPage/NotifyFavoriteListUserChangedQuery.cs
Mobile/Android/MainPage/NotifyJobListUserChangedQuery.cs
Mobile/Android/MainPage/Tab.cs
Mobile/Android/MainPage/ViewPagerFragment.cs
Mobile/Android/MainPage/ViewPagerFragmentViewModel.cs

Let's say you are looking for a job, if you type a query into the search bar, it should only refresh the job list since that's the tab you are right now.
If you are looking for saved jobs position (Favorites), and you type text into the search bar it should filter the saved jobs by title.

Main page search bar by context from now on

---

Mobile/Android/Resources/values/Strings.xml

Removes extra ApplicationName entry from the Strings.xml file, fixing #376. 
The duplicate entry with the key ApplicationName was making the app to be named as 'Android.'
Now the app is named correctly as Emplea.do

Corrects duplicate in Strings.xml

---

EmpleoDotNet/Content/Site.css
EmpleoDotNet/Content/Site.less

De acuerdo con el Issue #353 
El problema del padding-bottom causaba esto:
En este pull request se corrige tomando la forma siguiente:

Remove paddin-bottom

---

EmpleoDotNet.Repository/JobOpportunityRepository.cs

Job opportunities are ordered now by popularity level.
* At home screen job opportunities first are ordered by publish date (because the purpose of this screen is to see the latest job opportunities) and then by upvotes count.
* At job opportunities screen first are ordered by up votes count and then by Id.
Related issues: #379, #308

Order job opportunities by popularity level.

---

Mobile/Android/Android.csproj
Mobile/Android/Services/CacheService.cs
Mobile/Core/ICache.cs

Android ICache implementation now uses UserAccount instead of LocalMachine for persistency.
Android ICache implementation now receives an optional expiration parameter when saving an object.
Solves #426

Minor changes to the Cache Service.

---

Mobile/Android/Android.csproj
Mobile/Android/Assets/MobileConfig.json
Mobile/Android/Empleado.cs
Mobile/Android/EmpleadoApp.cs
Mobile/Android/Framework/Bootstrapping/Bootstrapping.cs
Mobile/Android/Properties/AndroidManifest.xml
Mobile/Android/SearchPage/SearchActivity.cs
Mobile/Android/Services/AssetReader.cs
Mobile/Core/Core.csproj
Mobile/Core/CrossPlatformStuff.cs
Mobile/Core/Github/OctocatContributorService.cs
Mobile/Core/IAssetReader.cs
Mobile/Core/IMobileConfigurationManager.cs
Mobile/Core/MobileConfig.cs
Mobile/Core/MobileConfigurationManager.cs
Mobile/Core/packages.config

- I've been receiving feedback that the repository must be clean of any API key, and it shall be CI responsability to put them.
I included a new file called **MobileConfig.json** into the **Assets** folder, if you are going to add a new API key, just make a new property in the file
then go to the **MobileConfig** in **Core/MobileConfig** and add the new property so the JSON parser doesn't blow up.
Then to get the API keys, all you have to do is
**ViewModel**
Inject **IMobileConfigService** as a dependency, and then access the **MobileConfigurationFile** and there you have it.

Introduce a global way to get APIs key easily

---

Mobile/Android/Android.csproj

- Removes redundant whole-folder includes from Android.csproj
- Sets JavaMaximumHeap Size to 1Gb to avoid getting an OutOfMemoryException
when building.
Fixes #439

Fixes compilation on Visual Studio.

---

EmpleoDotNet/Content/css/theme/style.css
EmpleoDotNet/Views/Account/Profile.cshtml
EmpleoDotNet/Views/Shared/_JobListPartial.cshtml

Corrected UI error causing Profile page title to be hidden behind the page's header.
This address the issue #387.

Corrected profile page UI error.

---

EmpleoDotNet.AppServices/UserProfileSocialService.cs
EmpleoDotNet.Repository/UserProfileRepository.cs
EmpleoDotNet/App_Start/Startup.Auth.cs
EmpleoDotNet/Base_Auth.config
EmpleoDotNet/Controllers/AccountController.cs
EmpleoDotNet/EmpleoDotNet.csproj
EmpleoDotNet/Views/Account/_ExternalLoginsListPartial.cshtml
EmpleoDotNet/packages.config

* Added linkedin login.
* Fixed error on profile screen loading job opportunities by user because of null JobOpportunityLikes.
Fixes #302

Login with LinkedIn account.

---

EmpleoDotNet/Controllers/JobOpportunityController.cs

Company logo is optional but leaving the field empty cause the validation to fail. Validation has to be made only when url is not empty.

Fix issue #453 company logo url is optional

---

EmpleoDotNet/App_Start/RouteConfig.cs
EmpleoDotNet/Constants.cs
EmpleoDotNet/Controllers/HomeController.cs
EmpleoDotNet/EmpleoDotNet.csproj
EmpleoDotNet/Helpers/ListExtentions.cs
EmpleoDotNet/Services/RssResult.cs

According to #417 
* When you go to http://domain/rss you get a xml rss feed
* I couldn't validate it with http://www.feedvalidator.org/ because it must be hosted to test it, so I used http://www.validome.org/rss-atom/validate which allow you to copy and paste your source.
* It was suppose to have an image for each item, but the RSS 2.0 Specification does not provide an image tag for each item, only for the channel.

Create RSS feed for job opportunities
